version: 2
jobs:
  build:

    docker:
      - image: ivanpondal/alpine-latex:1.1.0

    working_directory: /workdir

    steps:
      - checkout

      - setup_remote_docker

      - run: apk update
      - run: apk --no-cache add ca-certificates python3

      - run:
          name: Building PDF
          command: ./build.py

      - store_artifacts:
          path: build/
